image: node:20


workflow:
  rules:
    - changes:
        - src/**/*
    - when: never

# stages:
#   - build_devireka
#   - deploy_devireka
#   - build_ireka
#   - deploy_ireka
#   - build_ia
#   - deploy_ia
#   - build_aa
#   - deploy_aa
    
include:
  - local: '.gitlab/ci/devireka-ci.yml'
  - local: '.gitlab/ci/ireka-ci.yml'  
  - local: '.gitlab/ci/ia-ci.yml'
  - local: '.gitlab/ci/aa-ci.yml'

# === GitHub Sync Job ===
stages:
  - sync
  - build
  - deploy

sync_from_github:
  stage: sync
  tags:
    - reka-run
  image: alpine:latest
  before_script:
    - apk add --no-cache git bash
  script:
    - git config --global user.email "benzourry@gmail.com"
    - git config --global user.name "Razif Baital"
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/benzourry/leap-run-v3.git
    - git fetch github
    - git reset --hard github/main
    - git push -f origin main
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
