image: node:20


workflow:
  rules:
    - changes:
        - src/**/*
    - when: never

# stages:
#   - build_devireka
#   - deploy_devireka
#   - build_ireka
#   - deploy_ireka
#   - build_ia
#   - deploy_ia
#   - build_aa
#   - deploy_aa
    
include:
  - local: '.gitlab/ci/devireka-ci.yml'
  - local: '.gitlab/ci/ireka-ci.yml'  
  - local: '.gitlab/ci/ia-ci.yml'
  - local: '.gitlab/ci/aa-ci.yml'

# === GitHub Sync Job ===
stages:
  - sync
  - build
  - deploy

sync_from_github:
  stage: sync
  tags:
    - reka-run
  image: alpine:latest
  script:
    - apk add --no-cache git bash

    # Git config
    - git config --global user.email "ci-sync@leap.com"
    - git config --global user.name "LEAP CI Sync Bot"

    # Clone GitHub source repo
    - git clone https://oauth2:${GITHUB_TOKEN}@github.com/benzourry/leap-run-v3.git github-source

    # Replace only selected files/folders
    - rm -rf src && mkdir src
    - cp -r github-source/src/* src/
    - cp github-source/angular*.json . || true
    - cp github-source/ngsw-config*.json . || true
    - cp github-source/package.json .

    # Commit and push changes
    - git add src angular*.json ngsw-config*.json package.json
    - git commit -m "Sync from GitHub [CI]" || echo "No changes"
    - git push https://blmrazif:${GITLAB_PAT}@codebucket.unimas.my/blmrazif/leap-run.git HEAD:main
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'         # manual run
      when: manual
    - if: '$CI_PIPELINE_SOURCE == "schedule"'    # scheduled run
      when: always
