name: Deploy RUNNER to KBORNEO Server

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
      - '.gitlab/ci/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (legacy peer deps)
        run: npm ci --legacy-peer-deps

      - name: Use leap angular config
        run: cp angular-kborneo.json angular.json

      - name: Build Angular app
        run: npx ng build --configuration production

      - name: Clean remote directory (optional)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_HOST_KBORNEO }}
          username: ${{ secrets.SFTP_USER_KBORNEO }}
          password: ${{ secrets.SFTP_PASS_KBORNEO }}
          script: |
            rm -rf /var/www/vhosts/kborneo.my/httpdocs/run/*

      - name: Upload to KBORNEO server via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST_KBORNEO }}
          username: ${{ secrets.SFTP_USER_KBORNEO }}
          password: ${{ secrets.SFTP_PASS_KBORNEO }}
          source: dist/run/browser/*
          target: /var/www/vhosts/kborneo.my/httpdocs/run/
          strip_components: 3

      - name: Set file permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_HOST_KBORNEO }}
          username: ${{ secrets.SFTP_USER_KBORNEO }}
          password: ${{ secrets.SFTP_PASS_KBORNEO }}
          script: |
            chmod -R 755 /var/www/vhosts/kborneo.my/httpdocs/run
            chown -R kborneo:psacln /var/www/vhosts/kborneo.my/httpdocs/run
